# Generated by Django 4.1 on 2022-08-04 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Public_Relations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('deed', models.CharField(choices=[('A', 'Atrocity'), ('B', 'Bad'), ('G', 'Good'), ('M', 'Miracle')], default='G', max_length=1)),
                ('duck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.duck')),
            ],
        ),
    ]
