# Generated by Django 4.1 on 2022-08-05 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_public_relations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='public_relations',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='public_relations',
            name='date',
            field=models.DateField(verbose_name='Deed date'),
        ),
    ]
