# Generated by Django 4.1 on 2022-08-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_hat_alter_public_relations_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='duck',
            name='hats',
            field=models.ManyToManyField(to='main_app.hat'),
        ),
    ]
